/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6574. Copyright MediaTek Inc. (C) 2013.
 * Sun Jul 10 10:41:48 2016
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_USB_ID_CHANNEL     0
#define AUXADC_PCB_REVISION_CHANNEL     1
#define AUXADC_CHARGER_VOLTAGE_CHANNEL     2


#endif //_CUST_AUXADC_TOOL_H


