/*
 * Generated by MTK SP DrvGen Version 03.13.6  for MT6574. Copyright MediaTek Inc. (C) 2013.
 * Sun Jul 10 10:41:48 2016
 * Do Not Modify the File.
 */

#define GPIO_DVDD28_MSDC1     GPIO_VMC
#define GPIO_DVDD28_MSDC2     GPIO_VIO18
#define GPIO_DVDD28_BPI     GPIO_VIO18


